name: Quality Gate

on:
  pull_request:
    branches:
      - main

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install pytest ruff mypy

      - name: Check syntax
        run: python -m compileall .

      - name: Lint and type-check
        run: |
          ruff check .
          mypy .

      - name: Run tests
        run: pytest --maxfail=1 --disable-warnings -q

      - name: Check app starts
        run: |
          python -m main.py --help
