name: Quality Gate

on:
  pull_request:
    branches:
      - main

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

#      - name: Install system dependencies
#        run: |
#          sudo apt-get update
#          sudo apt-get install -y libegl1-mesa libgl1-mesa-dev libglib2.0-0 libxkbcommon0 libxcomposite1 libxcursor1 libxi6 libxrandr2 libxss1 libxtst6

      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install pytest

      - name: Run tests
        run: |
          source venv/bin/activate
          pytest --maxfail=1 --disable-warnings -q
